"""Report Generator for Kosmos E2E Testing

Generate formatted test reports and summaries.
"""

import json
from datetime import datetime
from pathlib import Path
from typing import Optional


def generate_report(
    results: dict,
    output_path: Optional[str] = None,
    format: str = "markdown",
) -> str:
    """Generate a test report

    Args:
        results: Test results dictionary from run_tests()
        output_path: Optional path to save report
        format: Output format ('markdown', 'json', 'text')

    Returns:
        Formatted report string
    """
    if format == "markdown":
        report = _generate_markdown(results)
    elif format == "json":
        report = _generate_json(results)
    else:
        report = _generate_text(results)

    if output_path:
        Path(output_path).write_text(report)
        print(f"Report saved to: {output_path}")

    return report


def _generate_markdown(results: dict) -> str:
    """Generate markdown format report"""
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    lines = [
        "# Kosmos E2E Test Report",
        "",
        f"**Generated:** {timestamp}",
        "",
        "## Summary",
        "",
        f"| Metric | Value |",
        f"|--------|-------|",
        f"| Tier | {results.get('tier', 'N/A')} |",
        f"| Provider | {results.get('provider', 'N/A')} |",
        f"| Passed | {results.get('passed', 0)} |",
        f"| Failed | {results.get('failed', 0)} |",
        f"| Skipped | {results.get('skipped', 0)} |",
        f"| Total | {results.get('total', 0)} |",
        f"| Duration | {results.get('duration', 0):.1f}s |",
        f"| Status | {'PASS' if results.get('success') else 'FAIL'} |",
        "",
    ]

    if results.get("coverage"):
        lines.extend([
            "## Coverage",
            "",
            f"**Total Coverage:** {results['coverage']}%",
            "",
        ])

    pass_rate = (results.get("passed", 0) / max(results.get("total", 1), 1)) * 100
    lines.extend([
        "## Analysis",
        "",
        f"- Pass rate: {pass_rate:.1f}%",
    ])

    if results.get("failed", 0) > 0:
        lines.append(f"- {results['failed']} test(s) failed - review needed")

    if results.get("skipped", 0) > 0:
        lines.append(f"- {results['skipped']} test(s) skipped")

    lines.extend([
        "",
        "---",
        "*Generated by Kosmos E2E Testing Skill*",
    ])

    return "\n".join(lines)


def _generate_json(results: dict) -> str:
    """Generate JSON format report"""
    report_data = {
        "timestamp": datetime.now().isoformat(),
        "results": results,
        "analysis": {
            "pass_rate": (results.get("passed", 0) / max(results.get("total", 1), 1)) * 100,
            "has_failures": results.get("failed", 0) > 0,
        },
    }
    return json.dumps(report_data, indent=2)


def _generate_text(results: dict) -> str:
    """Generate plain text report"""
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    lines = [
        "KOSMOS E2E TEST REPORT",
        "=" * 50,
        f"Generated: {timestamp}",
        "",
        "SUMMARY",
        "-" * 30,
        f"Tier:     {results.get('tier', 'N/A')}",
        f"Provider: {results.get('provider', 'N/A')}",
        f"Passed:   {results.get('passed', 0)}",
        f"Failed:   {results.get('failed', 0)}",
        f"Skipped:  {results.get('skipped', 0)}",
        f"Total:    {results.get('total', 0)}",
        f"Duration: {results.get('duration', 0):.1f}s",
        f"Status:   {'PASS' if results.get('success') else 'FAIL'}",
        "",
    ]

    if results.get("coverage"):
        lines.extend([
            "COVERAGE",
            "-" * 30,
            f"Total: {results['coverage']}%",
            "",
        ])

    return "\n".join(lines)


def print_summary(results: dict) -> None:
    """Print a concise test summary to console

    Args:
        results: Test results dictionary
    """
    status = "[PASS]" if results.get("success") else "[FAIL]"
    passed = results.get("passed", 0)
    failed = results.get("failed", 0)
    total = results.get("total", 0)
    duration = results.get("duration", 0)

    print()
    print("=" * 50)
    print(f"  {status} {results.get('tier', 'Test')} Results")
    print("=" * 50)
    print(f"  Passed:   {passed}/{total}")
    print(f"  Failed:   {failed}")
    print(f"  Duration: {duration:.1f}s")
    print(f"  Provider: {results.get('provider', 'unknown')}")
    print("=" * 50)
    print()


def compare_results(results_list: list[dict]) -> str:
    """Compare multiple test runs

    Args:
        results_list: List of results dictionaries

    Returns:
        Comparison report string
    """
    lines = [
        "# Test Comparison Report",
        "",
        "| Provider | Tier | Passed | Failed | Duration | Status |",
        "|----------|------|--------|--------|----------|--------|",
    ]

    for r in results_list:
        status = "PASS" if r.get("success") else "FAIL"
        line = (
            f"| {r.get('provider', 'N/A')} "
            f"| {r.get('tier', 'N/A')} "
            f"| {r.get('passed', 0)} "
            f"| {r.get('failed', 0)} "
            f"| {r.get('duration', 0):.1f}s "
            f"| {status} |"
        )
        lines.append(line)

    return "\n".join(lines)


if __name__ == "__main__":
    # Demo with sample results
    sample_results = {
        "tier": "e2e",
        "provider": "local-reasoning",
        "passed": 42,
        "failed": 2,
        "skipped": 5,
        "total": 49,
        "duration": 245.5,
        "success": False,
        "coverage": 78.5,
    }

    print(generate_report(sample_results, format="text"))
